version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "wooly-discogs-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rls5vr979pns"
s3_prefix = "wooly-discogs-lambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
